drop table tbl_status_desc;

create table tbl_status_desc
(
  status_code varchar(10),
  status_desc varchar(10000)
);

insert into tbl_status_desc values (200 ,'OK'); 
insert into tbl_status_desc values (201 ,'Created'); 
insert into tbl_status_desc values (202 ,'Accepted'); 
insert into tbl_status_desc values (203 ,'Non-Authoritative Information (since HTTP/1.1)'); 
insert into tbl_status_desc values (204 ,'No Content'); 
insert into tbl_status_desc values (205 ,'Reset Content'); 
insert into tbl_status_desc values (206 ,'Partial Content'); 
insert into tbl_status_desc values (207 ,'Multi-Status (WebDAV; RFC 4918)'); 
insert into tbl_status_desc values (208 ,'Already Reported (WebDAV; RFC 5842)'); 
insert into tbl_status_desc values (250 ,'Low on Storage Space (RTSP; RFC 2326)'); 
insert into tbl_status_desc values (226 ,'IM Used (RFC 3229)'); 
insert into tbl_status_desc values (300 ,'Multiple Choices'); 
insert into tbl_status_desc values (301 ,'Moved Permanently'); 
insert into tbl_status_desc values (302 ,'Found'); 
insert into tbl_status_desc values (303 ,'See Other(since HTTP/1.1)'); 
insert into tbl_status_desc values (304 ,'Not Modified'); 
insert into tbl_status_desc values (305 ,'Use Proxy (since HTTP/1.1)'); 
insert into tbl_status_desc values (306 ,'Switch Proxy'); 
insert into tbl_status_desc values (307 ,'Temporary Redirect (since HTTP/1.1)'); 
insert into tbl_status_desc values (308 ,'Permanent Redirect (approved as experimental RFC)'); 
insert into tbl_status_desc values (400 ,'Bad Request'); 
insert into tbl_status_desc values (401 ,'Unauthorized'); 
insert into tbl_status_desc values (402 ,'Payment Required'); 
insert into tbl_status_desc values (403 ,'Forbidden'); 
insert into tbl_status_desc values (404 ,'Not Found'); 
insert into tbl_status_desc values (405 ,'Method Not Allowed'); 
insert into tbl_status_desc values (406 ,'Not Acceptable'); 
insert into tbl_status_desc values (407 ,'Proxy Authentication Required'); 
insert into tbl_status_desc values (408 ,'Request Timeout'); 
insert into tbl_status_desc values (409 ,'Conflict'); 
insert into tbl_status_desc values (410 ,'Gone'); 
insert into tbl_status_desc values (411 ,'Length Required'); 
insert into tbl_status_desc values (412 ,'Precondition Failed'); 
insert into tbl_status_desc values (413 ,'Request Entity Too Large'); 
insert into tbl_status_desc values (414 ,'Request-URI Too Long'); 
insert into tbl_status_desc values (415 ,'Unsupported Media Type'); 
insert into tbl_status_desc values (416 ,'Requested Range Not Satisfiable'); 
insert into tbl_status_desc values (417 ,'Expectation Failed'); 
insert into tbl_status_desc values (418 ,'I am a teapot (RFC 2324)'); 
insert into tbl_status_desc values (420 ,'Enhance Your Calm (Twitter)'); 
insert into tbl_status_desc values (422 ,'Unprocessable Entity (WebDAV; RFC 4918)'); 
insert into tbl_status_desc values (423 ,'Locked (WebDAV; RFC 4918)'); 
insert into tbl_status_desc values (424 ,'Failed Dependency (WebDAV; RFC 4918)'); 
insert into tbl_status_desc values (424 ,'Method Failure (WebDAV)[15]'); 
insert into tbl_status_desc values (425 ,'Unordered Collection (Internet draft)'); 
insert into tbl_status_desc values (426 ,'Upgrade Required (RFC 2817)'); 
insert into tbl_status_desc values (428 ,'Precondition Required (RFC 6585)'); 
insert into tbl_status_desc values (429 ,'Too Many Requests (RFC 6585)'); 
insert into tbl_status_desc values (431 ,'Request Header Fields Too Large (RFC 6585)'); 
insert into tbl_status_desc values (444 ,'No Response (Nginx)'); 
insert into tbl_status_desc values (449 ,'Retry With (Microsoft)'); 
insert into tbl_status_desc values (450 ,'Blocked by Windows Parental Controls (Microsoft)'); 
insert into tbl_status_desc values (451 ,'Parameter Not Understood (RTSP)'); 
insert into tbl_status_desc values (451 ,'Unavailable For Legal Reasons (Internet draft)'); 
insert into tbl_status_desc values (451 ,'Redirect (Microsoft)'); 
insert into tbl_status_desc values (452 ,'Conference Not Found (RTSP)'); 
insert into tbl_status_desc values (453 ,'Not Enough Bandwidth (RTSP)'); 
insert into tbl_status_desc values (454 ,'Session Not Found (RTSP)'); 
insert into tbl_status_desc values (455 ,'Method Not Valid in This State (RTSP)'); 
insert into tbl_status_desc values (456 ,'Header Field Not Valid for Resource (RTSP)'); 
insert into tbl_status_desc values (457 ,'Invalid Range (RTSP)'); 
insert into tbl_status_desc values (458 ,'Parameter Is Read-Only (RTSP)'); 
insert into tbl_status_desc values (459 ,'Aggregate Operation Not Allowed (RTSP)'); 
insert into tbl_status_desc values (460 ,'Only Aggregate Operation Allowed (RTSP)'); 
insert into tbl_status_desc values (461 ,'Unsupported Transport (RTSP)'); 
insert into tbl_status_desc values (462 ,'Destination Unreachable (RTSP)'); 
insert into tbl_status_desc values (494 ,'Request Header Too Large (Nginx)'); 
insert into tbl_status_desc values (495 ,'Cert Error (Nginx)'); 
insert into tbl_status_desc values (496 ,'No Cert (Nginx)'); 
insert into tbl_status_desc values (497 ,'HTTP to HTTPS (Nginx)'); 
insert into tbl_status_desc values (499 ,'Client Closed Request (Nginx)'); 
insert into tbl_status_desc values (500 ,'Internal Server Error'); 
insert into tbl_status_desc values (501 ,'Not Implemented'); 
insert into tbl_status_desc values (502 ,'Bad Gateway'); 
insert into tbl_status_desc values (503 ,'Service Unavailable'); 
insert into tbl_status_desc values (504 ,'Gateway Timeout'); 
insert into tbl_status_desc values (505 ,'HTTP Version Not Supported'); 
insert into tbl_status_desc values (506 ,'Variant Also Negotiates (RFC 2295)'); 
insert into tbl_status_desc values (507 ,'Insufficient Storage (WebDAV; RFC 4918)'); 
insert into tbl_status_desc values (508 ,'Loop Detected (WebDAV; RFC 5842)'); 
insert into tbl_status_desc values (509 ,'Bandwidth Limit Exceeded (Apache bw/limited extension)'); 
insert into tbl_status_desc values (510 ,'Not Extended (RFC 2774)'); 
insert into tbl_status_desc values (511 ,'Network Authentication Required (RFC 6585)'); 
insert into tbl_status_desc values (550 ,'Permission denied'); 
insert into tbl_status_desc values (551 ,'Option not supported (RTSP)'); 
insert into tbl_status_desc values (598 ,'Network read timeout error (Unknown)'); 
insert into tbl_status_desc values (599 ,'Network connect timeout error (Unknown');
